/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucue.p3.GUI;

import edu.ucue.p3.Datos.SeleccionArchivo;
import edu.ucue.p3.Logica.BalanceadoBoolean;
import edu.ucue.p3.Logica.BalanceadoInt;
import edu.ucue.p3.Logica.BalanceadoLocalDate;
import edu.ucue.p3.Logica.BalanceadoString;
import edu.ucue.p3.Logica.GeneradorArchivo;
import edu.ucue.p3.Logica.IntercalacionBalanceada;
import edu.ucue.p3.Logica.Proceso;
import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import javafx.concurrent.Task;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author paul
 */
public class Ordenamiento extends javax.swing.JFrame {

    //private Balanceado ordenamiento;
    private IntercalacionBalanceada ordenamiento;
    private File f0;
    boolean done;
    /**
     * Creates new form Ordenamiento
     */
    public Ordenamiento() {
        initComponents();
        pbBarraProgreso.setStringPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCampoAOrdenar = new javax.swing.JComboBox<>();
        pbBarraProgreso = new javax.swing.JProgressBar();
        bAbrirArchivo = new javax.swing.JButton();
        bOrdenar = new javax.swing.JButton();
        bAleatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        cbCampoAOrdenar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbCampoAOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija el campo que desea ordenar:", "campo 1 (int)", "campo 2 (String)", "campo 3 (boolean)", "campo 4 (Fecha)" }));
        cbCampoAOrdenar.setEnabled(false);

        pbBarraProgreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbBarraProgresoStateChanged(evt);
            }
        });

        bAbrirArchivo.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        bAbrirArchivo.setText("Abrir Archivo");
        bAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirArchivoActionPerformed(evt);
            }
        });

        bOrdenar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        bOrdenar.setText("Ordenar");
        bOrdenar.setEnabled(false);
        bOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenarActionPerformed(evt);
            }
        });

        bAleatorio.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        bAleatorio.setText("Generar Archivo");
        bAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAleatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cbCampoAOrdenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAbrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pbBarraProgreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAbrirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCampoAOrdenar))
                .addGap(33, 33, 33)
                .addComponent(pbBarraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAleatorioActionPerformed
        try {
            // TODO add your handling code here:
            //ordenamiento = new Balanceado(pbBarraProgreso);
            f0 = GeneradorArchivo.getInstancia().generarArchivo();
            bAleatorio.setEnabled(false);
            bAbrirArchivo.setEnabled(false);
            cbCampoAOrdenar.setEnabled(true);
            bOrdenar.setEnabled(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al abrir el archivo");
        }
        
    }//GEN-LAST:event_bAleatorioActionPerformed

    private void bOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenarActionPerformed
        // TODO add your handling code here:
        if (cbCampoAOrdenar.getSelectedIndex() != 0) {
            try {
                //setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
               
                //ordenamiento.balanceado(cbCampoAOrdenar.getSelectedIndex()-1);
                switch (cbCampoAOrdenar.getSelectedIndex()) {
                    case 1:
                        ordenamiento = new BalanceadoInt(f0, pbBarraProgreso, 0);
                        break;
                    case 2:
                        ordenamiento = new BalanceadoString(f0, pbBarraProgreso, 1);
                        break;
                    case 3:
                        ordenamiento = new BalanceadoBoolean(f0, pbBarraProgreso, 2);
                        break;
                    case 4:
                        ordenamiento = new BalanceadoLocalDate(f0, pbBarraProgreso, 3);
                        break;
                }
                ordenamiento.balanceado();
                bAleatorio.setEnabled(true);
                bAbrirArchivo.setEnabled(true);
                cbCampoAOrdenar.setEnabled(false);
                bOrdenar.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane, "Se ha ordenado el archivo correctamente!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error al abrir el archivo");
            }           
            return;
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un campo!");
            return;
        }
    }//GEN-LAST:event_bOrdenarActionPerformed

    private void bAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirArchivoActionPerformed
        // TODO add your handling code here:
        f0 = new File((new SeleccionArchivo()).getPathArchivo(this));
        bAleatorio.setEnabled(false);
        bAbrirArchivo.setEnabled(false);
        cbCampoAOrdenar.setEnabled(true);
        bOrdenar.setEnabled(true);
    }//GEN-LAST:event_bAbrirArchivoActionPerformed

    private void pbBarraProgresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbBarraProgresoStateChanged
        // TODO add your handling code here:
        System.out.println("hi");
        JProgressBar pb = (JProgressBar) evt.getSource();
        pbBarraProgreso.setValue((int) pb.getValue());
    }//GEN-LAST:event_pbBarraProgresoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrirArchivo;
    private javax.swing.JButton bAleatorio;
    private javax.swing.JButton bOrdenar;
    private javax.swing.JComboBox<String> cbCampoAOrdenar;
    private javax.swing.JProgressBar pbBarraProgreso;
    // End of variables declaration//GEN-END:variables
}
